### ISSUE TITLE
[Question] RepeatableWrapLayout Group

### ISSUE THREAD

**Issue by predalpha** [muak/AiForms.Layouts#1]
Hello,

Im trying your control for a responsive Xamarin Application and it is pretty good. 
It's doing the job comparing to other controls ive already tried.

Thank you.

I'd like to know if you will develop a Grouping way like for the Xamarin listview and if your control is handling template selector.

Regards

**Comment by muak** [comment]
@predalpha 
Thank you for trying  AiForms.Layouts and to say "good".

Sorry, for now, there is no plan corresponded to Grouping or Template Selector.
But if I have some time,I might try to correspond to it.
Please don't expecting too much.

**Comment by predalpha** [comment]
thank you for your answer @muak  

if i got time, ill look for implementing those properties and share it with you.
Regards

**Comment by muak** [comment]
@predalpha 
I'm looking forward to that time!

**Comment by predalpha** [comment]
@muak 
Grouping is possible with your controls. Only thing to do is to nest a RepeatableWrapLayout inside a RepeatableStack and it works like a charm !

**Comment by predalpha** [comment]
Below a sample demonstrating nesting views grouped by dates.

![capture](https://user-images.githubusercontent.com/13038769/29992394-afd01ca0-8f9a-11e7-9307-a1a9e8a46030.png)

**Comment by predalpha** [comment]
Hello @muak 

TemplateSelector may be a very interesting feature to complete your controls. 
Below some sample code to help you implement this. 

```
public static object ItemsChanged(DataTemplate template, object item, BindableObject container)
        {
            var selector = template as DataTemplateSelector;

            if (selector != null)
            {
                template = selector.SelectTemplate(item, container);
            }

            //Binding context
            template.SetValue(BindableObject.BindingContextProperty, item);

            return template.CreateContent();
        }
```

**Comment by predalpha** [comment]
Hi @muak ,

I forked your repository to handle DataTemplate selector.
You can see the changes there https://github.com/predalpha/AiForms.Layouts
(only RepeatableStack.cs and RepeatableWrapLayout.cs got minors changes)

I have to make more tests (i cant test on IOS)
Tell me if you plan to import those modifications as i could point to your new nuget repo.

Regards

**Comment by muak** [comment]
@predalpha 
That makes sense.
WrapLayout with RepeatableStack is a nice solution!
Thank you for reporting it.

**Comment by muak** [comment]
@predalpha 
Thank you for telling me the idea corresponding to DataTemplateSelector.
I can be ready  to merge your fork project whenever.
Would you mind sending here your pull request  if possible?

**Comment by predalpha** [comment]
Sure @muak ,

im trying to do that but as it's the first time i github, i have to learn how to do this.
Edited : Done

**Comment by averlius** [comment]
> @muak
> Grouping is possible with your controls. Only thing to do is to nest a RepeatableWrapLayout inside a RepeatableStack and it works like a charm !

I'm sorry for this late comment, but how did you manage to group them? I have tried with no success. 
Thanks in advance
