### ISSUE TITLE
l:WrapLayout not found on IOS

### ISSUE THREAD

**Issue by TimBarton** [muak/AiForms.Layouts#11]
Hi 

I am getting this error on IOS.  I added the package to IOS.  On Android it is working.

Position 70:30. Type l:WrapLayout not found in xmlns clr-namespace:AiForms.Layouts;assembly=AiForms.Layouts

**Comment by TimBarton** [comment]
I looked in the Prebuild folder and noticed the dll was not being copied over.  I had to add 

var myaiforms = new AiForms.Layouts.WrapLayout();

in the AppDelegate and all is working now.

**Comment by muak** [comment]
@TimBarton
Have you used not a portable class library but a shared project as your project?
If have so, you might need to write that in AppDelegate.cs.

In case PCL, all you have to do is install to pcl project.

In any case thank you for useful information!

**Comment by TimBarton** [comment]
Hi @muak 

My project is  PCL.  

Thanks

**Comment by muak** [comment]
@TimBarton 
I'm sorry for  a late reply.
I was able to reproduce this issue finally.

There are two causes.

One is whether XamlCompilationOptions is Compile.
If not Compile, runtime error raise.
The way to solve is calling a method of this library in Platform or  turning XamlCompilationOptions to Compile.

The other is whether .netstandard is used.
If used, compie error or runtime error raise.
The way to solve is install this library to each platform.

**Comment by TimBarton** [comment]
@muak 

Thank you.
