### ISSUE TITLE
Is it possible for you to create a NETStandard version of the Layouts?

### ISSUE THREAD

**Issue by dfarrNTST** [muak/AiForms.Layouts#12]
We are moving over to use NETStandard for all of our Xamarin apps...could you create a NETStandard version of these?

**Comment by muak** [comment]
@dfarrNTST 
Thank you for using this library.
I'm just creating the package corresponded to .NETStandard now.
Please wait for a while.

**Comment by muak** [comment]
@dfarrNTST 
I released version 1.0.2-pre corresponded to netstandard.
Please try it.

**Comment by dfarrNTST** [comment]
Working so far...will give it a good workout over the next week or so.  Thanks for turning that around so quick!
