### ISSUE TITLE
Static Item within the repeat layout

### ISSUE THREAD

**Issue by libin85** [muak/AiForms.Layouts#14]
Is it possible to have a static item within the repeater layout? Lets say, I have a 3 column layout, the very first item will be a "Add Button" and all the remaining items will be from the List<T>. Is that possible?

**Comment by muak** [comment]
@libin85 
Thank you for trying this library.

I think that it is impossible that.
But I think using DataTemplateSelector enable you to do close to it.

https://github.com/muak/AiForms.Layouts/blob/master/Sample/Sample/Views/WrapLayoutWithSelector.xaml

**Comment by libin85** [comment]
Thanks for the reply @muak . I have tried using DataTemplateSelector yesterday. And it somewhat works. But when I add the ItemTapCommand to the wrap layout, the UI does not render.I have updated the Nuget to 1.0.2 -pre

**Comment by libin85** [comment]
Here is my code
` <StackLayout Grid.Row="7" Grid.Column="0" Grid.ColumnSpan="3">
   <l:RepeatableWrapLayout ItemTapCommand="TapCommand" ItemsSource="{Binding MobInBales}" Spacing="20" UniformColumns="3" IsSquare="true" ItemTemplate="{StaticResource selector}"/> </StackLayout>`

Do you find any error

**Comment by muak** [comment]
@libin85 
I'm sorry for delay of reply.

In your code
``ItemTapCommand="TapCommand"``
I think it is not correctly set binging .

Correct code is ...
``ItemTapCommand="{Binding TapCommand}"``

Please try it.

**Comment by libin85** [comment]
Thats works. Thank you :)
