### ISSUE TITLE
NaN Exception

### ISSUE THREAD

**Issue by PostImpatica** [muak/AiForms.Layouts#15]
## Error:
    $exception	{System.ArgumentException: NaN is not a valid value for width
       at Xamarin.Forms.Platform.UWP.TaskExtensions.<>c.<WatchForError>b__2_1(Object e)
       at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()}	
    System.ArgumentException

## Similar NaN error occurs on
Android
iOS
UWP

## My app config:
VSEnterprise 2017 v.15.5.2
Xamarin 4.8.0.753
Xamarin Forms 2.5.0.121934
Shared project is a .NetStandard 2.0

## My code
    <ScrollView>
            ...
        <Grid>   
                ...        
            <Grid>
                    ...
                <StackLayout>
                     ...
                    <l:WrapLayout Spacing="4" UniformColumns="3" HorizontalOptions="FillAndExpand">
                        <Label Text="test"></Label>
                        <Label Text="test"></Label>
                        <Label Text="test"></Label>
                   </l:WrapLayout>

**Comment by muak** [comment]
@helzgate 

Thank you for this report.

I fixed this issue and released a new version.
Please try it.

I'm sorry for the delay in replying.
Thanks.
