### ISSUE TITLE
GestureRecognizers in DataTemplate

### ISSUE THREAD

**Issue by idimkk** [muak/AiForms.Layouts#17]
Good afternoon!
I'm trying to add my clicker, using the TapGestureRecognizer. But this does not work, I redefined BindingContext, similar to ListView, it also does not work.
I do not like the built-in event because I need more complicated logic.
Could you help me?
[SampleCode](https://pastebin.com/Lys88qBg)

**Comment by muak** [comment]
@idimkk 
I'm sorry for so late reply.

Binding in DataTemplate, you must specify source the following:

```xml
<al:RepeatableStack ItemsSource="{Binding somelist}" x:Name="parent">
  <al:RepeatableStack.ItemTemplate>
     <DataTemplate>
	<Label>
            <Label.GestureRecognizers>
               <TapGestureRecognizer Command="{Binding BindingContext.someCommand,Source={x:Reference parent}}" />
            </Label.GestureRecognizers>
        </Label>		
    </DataTemplate>
 </al:RepeatableStack.ItemTemplate>
</al:RepeatableStack>
```

**Comment by idimkk** [comment]
Thank you. I already solved the problem in a similar way!
