### ISSUE TITLE
how to achieve uniform with flexlayout

### ISSUE THREAD

**Issue by TedMobile** [muak/AiForms.Layouts#20]
Hi
I think you have created something really really good here.
It's not an issue at all but I wonder if you can spare few mins in helping with a small example on how to use the flexlayout like you do with the wraplayout eg Uniform square.

I need to build a screen that looks like your wraplayout (uniform) and clicking one of them is bound to a command.

Any chance on one example? There is very little on flexlayout out there

many thanks

**Comment by TedMobile** [comment]
I added an itemtapped command and all works now

**Comment by muak** [comment]
@TedMobile 

Hi, thank you for using this library and sorry for late replying.

If I have some time, I think that I will write an example more detailed than what the ReadMe is.

I'm so glad that you implemented the functions you want!

Thank you😄
