### ISSUE TITLE
WrapLayout inside ScrollView

### ISSUE THREAD

**Issue by metaine** [muak/AiForms.Layouts#3]
Hi! Thanks for sharing this Layout. 
I was playing around with it but unfortunately, inside the ScrollView the WrapLayout is just clipped and doesn't actually scroll. Is it inherent due to the way the thing is made up or just  some measurement hasn't been implemented yet?

**Comment by muak** [comment]
@metaine 

Thank you for trying this.
In case my environment ,WrapLayout inside scrollview can scroll.
Will you tell me the xaml (or the code) occuring that issue?

**Comment by metaine** [comment]
Sorry, this is my fault. I was setting ScrollView orientation incorrectly.

**Comment by muak** [comment]
@metaine 
It doesn't matter.
I'm glad that it ran correctly.
