### ISSUE TITLE
Header of RepeatablewrapLayout

### ISSUE THREAD

**Issue by mo-kml** [muak/AiForms.Layouts#5]
Hi there. I wanna add a header to my wrap layout but i cant do that.
actually i wanna make a stacklayout`s width align to my wraplayout`s width. but i dont wanna make it static. so I`d make the stacklayout as wraplayout`s header
how do i do that?

**Comment by muak** [comment]
@mo-kml 
Thank you for trying this library.
Wraplayout doesn't have a function adding a header.
Therefore I think, like you said, using stacklayout is a solution.

like following 

```xml
<StackLayout>
    <Label Text="Header" />
     <WrapLayout>
     ...
     </WrapLayout>
     <Label Text="Footer" />
</StackLayout>
```
