### ISSUE TITLE
WrapLayout doesnt show the latest line of objects completely

### ISSUE THREAD

**Issue by mo-kml** [muak/AiForms.Layouts#6]
Hi
im using RepeatableWrapLayout . it doesnt show the latest line of objects and show the half of them.
what should i do?

**Comment by muak** [comment]
@mo-kml 
Could you show me ReapeatableWrapLayout's parameters with xaml here?

**Comment by mo-kml** [comment]
>             <wrapLayout:RepeatableWrapLayout 
>                 Spacing="30" 
>                 IsSquare="true" 
>                 HorizontalOptions="Center" 
>                 VerticalOptions="Start" 
>                 Padding="20" 
> 				ItemsSource="{Binding StaffListItem}"
> 			    UniformColumns="{Binding UniformColumns}"
> 				>
>                 <wrapLayout:RepeatableWrapLayout.ItemTemplate>
>                     <DataTemplate>
>                             <StackLayout>
>                                 <AbsoluteLayout VerticalOptions="Center" HorizontalOptions="Center">
>                                 <local:RoundedButton Command="{Binding Path=BindingContext.TapCommand,Source={x:Reference Name=StaffLoginView}}" CommandParameter="{Binding .,Path=DataContext}" AbsoluteLayout.LayoutBounds="0,0,1,1" AbsoluteLayout.LayoutFlags="PositionProportional,SizeProportional" WidthRequest="110" HeightRequest="110" >
>                                         <circleImage:CircleImage.BackgroundColor>
>                                             <Color x:FactoryMethod="FromHex">
>                                                 <x:Arguments>
>                                                     <x:String>#4057C2EF</x:String>
>                                                 </x:Arguments>
>                                             </Color>
>                                         </circleImage:CircleImage.BackgroundColor>
>                                     </local:RoundedButton>
>                                     <circleImage:CircleImage AbsoluteLayout.LayoutBounds="0,0,1,1" AbsoluteLayout.LayoutFlags="PositionProportional,SizeProportional"
>                                                     Source="{Binding Image}"
>                                                      Aspect="AspectFill" 
>                                                      BorderThickness="0"
>                                                      HeightRequest="100"
>                                                      WidthRequest="100"
>                                                      FillColor="{Binding ImageBackgroundColor}"
>                                                      HorizontalOptions="Center"
>                                                      VerticalOptions="Center"/>
>                                     <Label VerticalOptions="Center" TextColor="White" HorizontalOptions="Center" Text="{Binding Letter}" FontSize="35" AbsoluteLayout.LayoutBounds="0.5,0.5,100,100" AbsoluteLayout.LayoutFlags="PositionProportional"/>
> 
>                                     <iconize:IconImage Icon="ion-locked" IconColor="#595AC4F0" IsVisible="{Binding IsFastLogin,Converter={StaticResource inverter},ConverterParameter=IsFastLogin}"  IconSize="15" VerticalOptions="Center" HorizontalOptions="Center" AbsoluteLayout.LayoutBounds="1.5,1.5,50,50" AbsoluteLayout.LayoutFlags="PositionProportional"/>
> 
>                                     
> 
>                                 </AbsoluteLayout>
> 
>                                 <Label
> 								VerticalOptions="Center"
>                                 HorizontalOptions="Center"
>                                 TextColor="White"
>                                 FontSize="15"
> 								Text="{Binding Name}"  />
>                             
>                         </StackLayout>
>                     </DataTemplate>
>                 </wrapLayout:RepeatableWrapLayout.ItemTemplate>
>             </wrapLayout:RepeatableWrapLayout>

**Comment by muak** [comment]
@mo-kml 
Thakyou so much.
I will suvey this code.
Please wait for a while.

**Comment by muak** [comment]
@mo-kml 

I surveyed this issue using contentview instead of external library's controls and customview.
But I couldn't reproduce that issue.

There might be some problems in RoundedButton, CircleImage or IconImage.

<img src="https://dl.dropboxusercontent.com/s/oa20yi7r9dn52x9/ss_wraplayout_survey.png" width="150" />

```xml
<ScrollView>
<w:RepeatableWrapLayout 
		Spacing="30" 
		IsSquare="true" 
		HorizontalOptions="Center" 
		VerticalOptions="Start" 
		Padding="20" 
		ItemsSource="{Binding BoxList}"
		UniformColumns="{Binding UniformColumns}"
	>
	<w:RepeatableWrapLayout.ItemTemplate>
		<DataTemplate>
			<StackLayout>
				<AbsoluteLayout VerticalOptions="Center" HorizontalOptions="Center">
					<ContentView BackgroundColor="{Binding Color}" 
						AbsoluteLayout.LayoutBounds="0,0,1,1" AbsoluteLayout.LayoutFlags="PositionProportional,SizeProportional"
						WidthRequest="110" HeightRequest="110" />
					<ContentView AbsoluteLayout.LayoutBounds="0,0,1,1" AbsoluteLayout.LayoutFlags="PositionProportional,SizeProportional"
									 HeightRequest="100"
									 WidthRequest="100"
									 BackgroundColor="Green"
									 HorizontalOptions="Center"
									 VerticalOptions="Center"/>
					<Label VerticalOptions="Center" TextColor="White" HorizontalOptions="Center" Text="{Binding Name}" FontSize="35" AbsoluteLayout.LayoutBounds="0.5,0.5,100,100" AbsoluteLayout.LayoutFlags="PositionProportional"/>

					<Label VerticalOptions="Center" HorizontalOptions="Center" AbsoluteLayout.LayoutBounds="1.5,1.5,50,50" AbsoluteLayout.LayoutFlags="PositionProportional" Text="icon"/>
										   
				</AbsoluteLayout>

				<Label VerticalOptions="Center" HorizontalOptions="Center" TextColor="White" FontSize="15" Text="{Binding Name}"  />
				
			</StackLayout>
		</DataTemplate>
	</w:RepeatableWrapLayout.ItemTemplate>
</w:RepeatableWrapLayout>
</ScrollView>
```
