### ISSUE TITLE
Parameters Binding Order [Documentation]

### ISSUE THREAD

**Issue by predalpha** [muak/AiForms.Layouts#7]
Hello @muak,

I really enjoy those controls. One thing what could be helpfull would be to mention that parameters (binding ones) must be declared in a correct order.

1. ItemTapCommand
2. ItemSource

If you set the property ItemTapCommand after Itemsource, it wont works as there is no ItemCommandPropertyChanged.

Anyway those are essentials controls which could be part of Xamarin.Forms, thanks for the work you achieve.

**Comment by muak** [comment]
@predalpha 
Thank you for reporting the issue.
I will try to reproduce this issue and fix it as soon as possible.
Please waitng for some time.

Thank you for everything!
